### ISSUE TITLE
ValueError: Expecting value: line 1 column 1 (just after installation)

### ISSUE THREAD

**Issue by nichu** [cpfair/tapiriik#108]
Hi 
I followed installation guide on wiki (I'm on ubuntu 14.04) 
"Running tapiriik locally without Vagrant"

After last command when I connect to port 8000 (using browser) I see only error 
"A server error occurred.  Please contact the administrator."

And on console i have:
Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/staticfiles/handlers.py", line 72, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 236, in __call__
    self.load_middleware()
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 59, in load_middleware
    mw_instance = mw_class()
  File "/home/user/tapiriik/tapiriik/web/startup.py", line 8, in __init__
    from tapiriik.services import Service
  File "/home/user/tapiriik/tapiriik/services/__init__.py", line 12, in <module>
    GarminConnect = GarminConnectService()
  File "/home/user/tapiriik/tapiriik/services/GarminConnect/garminconnect.py", line 118, in __init__
    self._activityHierarchy = json.loads(rawHierarchy)["dictionary"]
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

All services:
mongod and redis-server and rabbitmq-server 
are running

regards,

**Comment by cpfair** [comment]
I'm on mobile so I can't fix this right away - but line 117 has an URL
containing 'modern/' - remove that part of the path and it should work.

**Comment by nichu** [comment]
Great! thank you for quick response.

**Comment by jimmykane** [comment]
Having the same here. Ticket should not be closed until fixed
