### ISSUE TITLE
`manage.py runserver` constantly failing with `RuntimeError: dictionary changed size during iteration`

### ISSUE THREAD

**Issue by campbellr** [cpfair/tapiriik#137]
While running a dev instance of tapiriik i quite often see `manage.py runserver` fail with the following error:

```
Django version 1.5.1, using settings 'tapiriik.settings'
Development server is running at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 222, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 255, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 70, in handle
    self.run(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 79, in run
    autoreload.main(self.inner_run, args, options)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 145, in main
    reloader(main_func, args, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 114, in python_reloader
    reloader_thread()
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 95, in reloader_thread
    if code_changed():
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 57, in code_changed
    filenames = [getattr(m, "__file__", None) for m in sys.modules.values()]
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 57, in <listcomp>
    filenames = [getattr(m, "__file__", None) for m in sys.modules.values()]
RuntimeError: dictionary changed size during iteration
```

This looks like it might be Django defect [21049](https://code.djangoproject.com/ticket/21049), which was apparently fixed back in Django 1.6-beta-1

Any chance of upgrading to a newer version of Django?

**Comment by cpfair** [comment]
Which version of Django are you running? The requirements file specifies 1.5.1, which while woefully outdated has been working fine for me.

**Comment by campbellr** [comment]
I'm just using the version from the requirements file (you can see it at the top of the output i pasted), with python 3.4

**Comment by cpfair** [comment]
Oops, sorry, didn't see that. I've never once ran into that problem in 2+ years of using the development server on both Windows and Mac, so I don't really have any suggestions. Have you tried to see if the newer, fixed version of Django will run the site?

**Comment by campbellr** [comment]
I haven't yet, but I'll try that next. If that fixes the problem and there aren't any other issues then I will submit a pull request

**Comment by campbellr** [comment]
For what it's worth, I suspect it might be a timing issue caused by my slow VM, since waiting several seconds after starting the app seems to avoid the problem most of the time
