### ISSUE TITLE
auto_pause.py, line 15, SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by markcs** [cpfair/tapiriik#153]
Unable to access the web server.  'A server error occurred.  Please contact the administrator.' message is seen when loading the server webpage.

~/git/tapiriik$ python3 manage.py runserver 0.0.0.0:8000
Validating models...

0 errors found
July 21, 2015 - 21:19:51
Django version 1.5.1, using settings 'tapiriik.settings'
Development server is running at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/lib/python3.2/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.2/dist-packages/django/contrib/staticfiles/handlers.py", line 72, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.2/dist-packages/django/core/handlers/wsgi.py", line 236, in __call__
    self.load_middleware()
  File "/usr/local/lib/python3.2/dist-packages/django/core/handlers/base.py", line 59, in load_middleware
    mw_instance = mw_class()
  File "/home/mark/git/tapiriik/tapiriik/web/startup.py", line 8, in __init__
    from tapiriik.services import Service
  File "/home/mark/git/tapiriik/tapiriik/services/__init__.py", line 3, in <module>
    from tapiriik.services.RunKeeper import RunKeeperService
  File "/home/mark/git/tapiriik/tapiriik/services/RunKeeper/__init__.py", line 1, in <module>
    from .runkeeper import *
  File "/home/mark/git/tapiriik/tapiriik/services/RunKeeper/runkeeper.py", line 5, in <module>
    from tapiriik.services.auto_pause import AutoPauseCalculator
  File "/home/mark/git/tapiriik/tapiriik/services/auto_pause.py", line 15
    yield from ()
             ^
SyntaxError: invalid syntax
[21/Jul/2015 21:19:59] "GET / HTTP/1.1" 500 59

Git was pull'ed up until this merge:
commit 206881d7baa1b5ba1e339c653d10ec8456804020
Merge: 607446e fce4c1b
Author: Collin <cpf@cpfx.ca>
Date:   Sat Jul 18 07:49:31 2015 -0400

    Merge pull request #150 from campbellr/fix-laps

    smashrun: fix lap calculation

**Comment by campbellr** [comment]
I believe "yield from" wasn't introduced until python 3.3. You'll probably have to upgrade your python.
