### ISSUE TITLE
ImportError: cannot import name 'SMASHRUN_CLIENT_ID'

### ISSUE THREAD

**Issue by markcs** [cpfair/tapiriik#163]
HI!

I just had to reinstall and now I can't get this to work. I'm sure it is something I'm doing wrong, but can't figure it out!

The error I'm seeing is:
Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/staticfiles/handlers.py", line 72, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 236, in __call__
    self.load_middleware()
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 59, in load_middleware
    mw_instance = mw_class()
  File "/home/mark/git/tapiriik/tapiriik/web/startup.py", line 8, in __init__
    from tapiriik.services import Service
  File "/home/mark/git/tapiriik/tapiriik/services/__init__.py", line 27, in <module>
    from tapiriik.services.Smashrun import SmashrunService
  File "/home/mark/git/tapiriik/tapiriik/services/Smashrun/__init__.py", line 1, in <module>
    from .smashrun import SmashrunService
  File "/home/mark/git/tapiriik/tapiriik/services/Smashrun/smashrun.py", line 9, in <module>
    from tapiriik.settings import WEB_ROOT, SMASHRUN_CLIENT_ID, SMASHRUN_CLIENT_SECRET
ImportError: cannot import name 'SMASHRUN_CLIENT_ID'

I have run 'pip3 install -r requirements.txt' and smashrun exist under the packages directory:

/git/tapiriik# ls /usr/local/lib/python3.4/dist-packages/|grep smash
smashrun
smashrun_client-0.2.0.dist-info

I've restarted all services.

Advice appreciated!

**Comment by mduggan** [comment]
Try adding a `SMASHRUN_CLIENT_ID` and `SMASHRUN_CLIENT_SECRET` to the `local_settings.py`.

https://github.com/cpfair/tapiriik/blob/master/tapiriik/local_settings.py.example#L43

**Comment by markcs** [comment]
Perfect. Thank you
