### ISSUE TITLE
Sync with Garmin Connect is failing

### ISSUE THREAD

**Issue by srjinatl** [cpfair/tapiriik#393]
I have both a paid account and have installed Tapirik locally - and both are failing to sync with Garmin Connect. On my local Tapirik - I noticed that when the program goes to pull the list of activities from Garmin - the following error occurs:

Sync worker 14818 ready at 2017-10-28 15:38:32.289845
Beginning sync for 59f4a5d36362393ac3943383(exhaustive: True)
Ensuring partial sync poll subscription
	Retrieving list from garminconnect
Req with {'start': 0, 'limit': 100}
Service exception
Traceback (most recent call last):
  File "/vagrant/tapiriik/services/GarminConnect/garminconnect.py", line 300, in DownloadActivityList
    res = res.json()["results"]
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/tapiriik/sync/sync.py", line 665, in _downloadActivityList
    svcActivities, svcExclusions = svc.DownloadActivityList(conn, exhaustive)
  File "/vagrant/tapiriik/services/GarminConnect/garminconnect.py", line 303, in DownloadActivityList
    raise APIException("Parse failure in GC list resp: %s - %s" % (res.status_code, res.text))
tapiriik.services.api.APIException: Parse failure in GC list resp: 500 -  (user None )
SynchronizationCompleteException thrown
Writing back service data
Clearing old activity records
Writing back activity records
Finalizing
Unlocking user

I am not yet familiar enough with the code base to know for sure what the problem is - but I suspect that this may also be the cause of why I have not had any successful sync's of my activities with Garmin connect for several months now.

Any idea on what the problem might be? Did Garmin change something to cause an incompatibility with the current Tapirik code base?

**Comment by lewisl** [comment]
Don’t know if it’s the same problem, but GC is broken for me since yesterday. Looks like the same problem that rwgps was having. 

Garmin Connect: There was a problem indexing your activities on Garmin Connect, so no activities will be uploaded to Garmin Connect.

**Comment by srjinatl** [comment]
Actually my paid account with Tapirik thinks that it is working and it shows that it has sync'd all of the last few months of activity - but the activities never show up on Garmin Connect - they are sync'ing now ok between Strava and Runkeeper....going to try removing and re-adding Garmin Connect and see what happens.

**Comment by srjinatl** [comment]
Well - no luck - disconnecting and then reconnecting to my Garmin Connect account did no good - nothing has sync'd to Garmin since September - but if I look in the UI on Tapirik it thinks that it has sync'd all of those successfully to Garmin - so not sure what the problem is - but at the end of the day I will end up having to manually enter this stuff into Garmin - which defeats the purpose and eliminates the ability for a lot of the data to be in my Garmin account that would be there from a sync.

**Comment by sowabar** [comment]
I have the same issue. Activities do not sync to Garmin, with reported problem of "indexing your activities on Garmin Connect". Is anyone else having this problem?

**Comment by xplana** [comment]
same problem here

**Comment by ianhallsg** [comment]
Same problem for me... At least now i know it isn't something to do with my account. Sounds like maybe Garmin changed something and it stopped working?

**Comment by stitzenbaum** [comment]
I have not been able to sync garmin to runkeeper since July.  Now I have this error: "indexing your activities on Garmin Connect".  Just seems to be extremely unstable.  I have always hesitated on the paid version because the free version is so unreliable.

**Comment by srjinatl** [comment]
Actually - when I look at the page that you get to with the link that you can click on when it says that it could not sync some of your activities - it shows that strava and garmin connect were successfully sync'd and runkeeper sync failed. The latter was true enough - the activities didn't sync to Runkeeper - but the status continues to show successful sync's to garmin but never show up in my activities list. So they are definitely NOT sync'ing successfully. Frankly this software has become problematic at best - completely unreliable.

**Comment by magnific0** [comment]
I have the same issues, no new activities were synced from Garmin Connect to any other connected services since December 25, 2017. 

In the activities list past GC activities are shown marked with a ✗ and the message:

> Garmin Connect: There was a problem indexing your activities on Garmin Connect, so no activities will be uploaded to Garmin Connect. 

Despite being originally activities synced from GC.

I tried reconnecting Garmin a few times, set the private activities checkbox and made my profile and activities public, but no luck yet.

**Comment by JRR01** [comment]
Same issue. Any update?

**Comment by magnific0** [comment]
I couldn't solve the issue so I connected [Endomondo with Garmin[(https://support.endomondo.com/hc/en-us/articles/115003632833-Automatic-upload-from-Garmin-Connect-) and Endomondo with Tapiriik, which seems to work syncing to all other services.

**Comment by jbtibor** [comment]
@magnific0 Can Endomondo sync to Garmin? Can't see on the website it could.

**Comment by magnific0** [comment]
@jbtibor No but [Garmin can sync to Endomondo](https://support.endomondo.com/hc/en-us/articles/115003632833-Automatic-upload-from-Garmin-Connect-), and from Endomondo you can sync to any other service using Tapiriik. So just to be clear this works only for getting your activities out of Garmin into other services.

**Comment by jbtibor** [comment]
I'm trying to set up an automatic sync to Garmin. Tapiriik seems to be broken at the moment.

**Comment by ianhallsg** [comment]
Mine seems to be working now. Anyone else?

**Comment by sowabar** [comment]
Same here, working now. @cpfair did you fix something or did Garmin fix on their end?

**Comment by AndreasWilladsen** [comment]
I'm having the same issue. Activities doesn't get uploaded to Garmin

**Comment by ficanas** [comment]
Same here

 There was a problem indexing your activities on Garmin Connect, so no activities will be uploaded to Garmin Connect. 

Paid account

**Comment by opernitt** [comment]
My activities have not synced since November 2018 and even going the Endomondo route does not work:
> Endomondo: There was an error while synchronizing this activity.
> Garmin Connect: There was a problem indexing your activities on Garmin Connect, so no activities will be uploaded to Garmin Connect.
I re-added Garmin Connect twice and just signed up for Endomondo but nothing seems to work. Just renewed my paid account and nothing syncs.

**Comment by torx25** [comment]
Same problem, Strava + Endomondo, paid account.
![2019-06-24 13_28_09-activities • tapiriik - https___tapiriik com_ - Vivaldi](https://user-images.githubusercontent.com/52157013/60007848-960e6d00-9662-11e9-96f4-f9488a09f10c.png)
![2019-06-24 13_28_29-dashboard • tapiriik - https___tapiriik com_ - Vivaldi](https://user-images.githubusercontent.com/52157013/60007849-960e6d00-9662-11e9-9787-fcceb37d797f.png)
![2019-06-24 13_28_22-dashboard • tapiriik - https___tapiriik com_ - Vivaldi](https://user-images.githubusercontent.com/52157013/60007850-96a70380-9662-11e9-9bdd-c0c3beb7c4c5.png)

**Comment by as31415rin** [comment]
Same here syncing from Endomondo to Strava since 2 days (paid tapiirik account and syncing from endomondo to dropbox and strava)

 **Strava: There was a problem indexing your activities on Strava, so no activities will be uploaded to Strava.**
