### ISSUE TITLE
Trying to run tapiriik locally - django error

### ISSUE THREAD

**Issue by o2droid** [cpfair/tapiriik#547]
I'm trying to run tapiriik locally  without valgrind. Unfortunately receiving following error. Am I missing something? I checked and module django-pipeline is installed.
```
python3 manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_li
ne
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pipelinedjango'
```

**Comment by svenjambor** [comment]
try playing around with the django pipeline version you're using. I'm trying to build it locally as well - and got stuck on the dropbox module. Did you manage to get around that?  Oldest version of django pipeline I got working was django-pipeline==1.6.14  (repo specifies 1.5.1 but that won't build whatever I do)

**Comment by lildude** [comment]
This is happening because you've uncommented the admin lines but haven't added the comma after `pipeline`:

https://github.com/cpfair/tapiriik/blob/a86a0ffcd75621ba0dd2b7b6e4be38e872f37b60/tapiriik/settings.py#L161-L167
